// GENERATED by scripts/sync-shared-types.mjs from partneriq-node/src/index.ts. Do not edit.

export type PartnerIQEnvironment = 'test' | 'live';

export interface PartnerIQErrorPayload {
  code: string;
  message: string;
  requestId?: string;
  details?: unknown;
}

// Request types
// ---------------------------------------------------------------------------

export interface PartnerIQRequestOptions {
  /**
   * Makes a write safe to retry: PartnerIQ returns the original response for a
   * repeated key (24h window) and rejects a reused key whose payload differs.
   */
  idempotencyKey?: string;
  /** Per-call timeout in milliseconds, overriding the client default. */
  timeout?: number;
  /** Abort the request from your side (e.g. when an incoming HTTP request is cancelled). */
  signal?: AbortSignal;
}

export interface ConversionCreateRequest {
  /** Your unique order / transaction id. A second conversion with the same id is rejected. */
  externalId: string;
  /** Your customer id. Links this purchase to a click identified earlier. */
  customerExternalId: string;
  /** Amount in the smallest currency unit (paise for INR). Must be a positive integer. */
  amount: number;
  /** ISO 4217 code. Defaults to the platform currency (INR) when omitted. */
  currency?: string;
  type?: 'PURCHASE' | 'SUBSCRIPTION_RENEWAL' | (string & {});
  /** ISO-8601 time the purchase happened. Defaults to the time PartnerIQ receives it. */
  occurredAt?: string;
  /**
   * Preferred: the Click ID (`pi_click_id`) captured by the browser SDK or the
   * /r/:shortCode redirect. Resolves attribution deterministically.
   */
  clickId?: string;
  /** Legacy: an explicit attribution record id. Prefer clickId. */
  attributionId?: string;
  productId?: string;
  metadata?: Record<string, unknown>;
}

export interface RefundCreateRequest {
  /** Your refund transaction id. Used to derive an idempotency key when none is given. */
  refundExternalId?: string;
  /** Partial refund amount in the smallest currency unit. Omit to refund the remaining balance. */
  amount?: number;
  reason?: string;
}

export type IdentifyCustomerRequest =
  | { customerId: string; anonymousId: string; attributionId?: never }
  | { customerId: string; attributionId: string; anonymousId?: never };

export interface AttachOrderRequest {
  attributionId: string;
  provider: 'RAZORPAY' | 'CASHFREE' | 'JUSPAY' | 'CUSTOM';
  externalOrderId: string;
  /** Amount in the smallest currency unit. */
  amount: number;
  currency: string;
}

export interface TrackingLinkCreateRequest {
  programId: string;
  affiliateId: string;
  destinationUrl: string;
  campaignId?: string;
  /** Vanity short code, e.g. "alex20". Must be unique within your organization. */
  customCode?: string;
  utmSource?: string;
  utmMedium?: string;
  utmCampaign?: string;
  /** @deprecated Ignored. The organization comes from the API key. */
  organizationId?: string;
}

export interface TrackingLinkListParams {
  programId?: string;
  affiliateId?: string;
  page?: number;
  /** 1-100, default 20. */
  limit?: number;
}

export type WebhookEventType =
  | 'affiliate.created'
  | 'affiliate.approved'
  | 'click.flagged'
  | 'conversion.created'
  | 'conversion.approved'
  | 'conversion.rejected'
  | 'conversion.refunded'
  | 'commission.created'
  | 'commission.approved'
  | 'commission.reversed'
  | 'payout.created'
  | 'payout.completed'
  | 'payout.failed'
  | 'payout.held'
  | 'payout.released';

export interface WebhookEndpointCreateRequest {
  /** Public HTTPS URL. Private, loopback and cloud-metadata addresses are rejected. */
  url: string;
  subscribedEvents: WebhookEventType[];
}

// ---------------------------------------------------------------------------
// Response types (fields PartnerIQ guarantees; records may carry more)
// ---------------------------------------------------------------------------

export interface Conversion {
  id: string;
  organizationId: string;
  programId?: string | null;
  affiliateId?: string | null;
  externalId: string;
  customerExternalId?: string | null;
  amount: number;
  currency: string;
  status: string;
  environment?: string;
  clickId?: string | null;
  createdAt: string;
  [key: string]: unknown;
}

export interface ConversionCreateResponse {
  conversion: Conversion;
  fraudResult?: Record<string, unknown> | null;
  commission?: Record<string, unknown> | null;
}

export interface IdentifyCustomerResponse {
  customerExternalId: string;
  updatedAttributions: number;
}

export interface AttachOrderResponse {
  attached: boolean;
  duplicate?: boolean;
  attributionId: string;
  provider?: string;
  externalOrderId?: string;
}

export interface TrackingLink {
  id: string;
  organizationId: string;
  programId: string;
  affiliateId: string;
  shortCode: string;
  shortUrl?: string | null;
  destinationUrl: string;
  campaignId?: string | null;
  status: string;
  environment?: 'test' | 'live';
  clicks?: number;
  conversions?: number;
  revenue?: number;
  createdAt: string;
  [key: string]: unknown;
}

export interface Program {
  id: string;
  organizationId: string;
  name: string;
  status?: string;
  environment?: 'test' | 'live';
  [key: string]: unknown;
}

export interface Affiliate {
  id: string;
  organizationId: string;
  displayName: string;
  email: string;
  companyName: string | null;
  website: string | null;
  country: string | null;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface WebhookEndpoint {
  id: string;
  url: string;
  environment: 'test' | 'live';
  enabled?: boolean;
  subscribedEvents: WebhookEventType[];
  createdAt: string;
}

export interface WebhookEndpointWithSecret extends WebhookEndpoint {
  /** Signing secret. Returned only once, at creation: store it in your secret manager. */
  secret: string;
}

export interface Page<T> {
  data: T[];
  meta?: { page?: number; limit?: number; total?: number; totalPages?: number; nextCursor?: string | null };
}

/** The JSON body PartnerIQ POSTs to your webhook endpoint. */
export interface WebhookEvent<T = Record<string, unknown>> {
  /** Stable per event, identical across retries: de-duplicate on this. */
  id: string;
  event: WebhookEventType;
  environment: 'test' | 'live';
  /** Unix seconds when the event was created (not when this attempt was sent). */
  timestamp: number;
  data: T;
}
